name: Autotests for users.bugred.ru

on:
  push:
  pull_request:
  branches:
    -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    name: Seting up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
      name: Installing dependencies
    run: python -m pip install --upgrade pip
         pip install -r requirements.txt
         pytest api 
